/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.inventares.gerenciamentocontabancaria;

import javax.swing.JOptionPane;
/**
 *
 * @author manoelps
 */
public class FormMain extends javax.swing.JFrame {
    
    // declaro de um atributo para auxiliar com o deposito e saque
    private double deposito = 0.0;
    private double saque = 0.0;
    private double saldo = 0.0;
    
    // declaro os atributos de taxas do banco
    private final double taxaManutencao = 5.0; // taxa cobrada em R$
    private final double taxaJuros = 5; //Taxa de rendimento em %
    
    //declaro atributo de controle do titulo dos dialogs
    private String tituloJanela = "";
    
    // instancio as classes ContaCorrente e ContaPoupanca para ter acesso aos seus objetos
    //passando como parametro as contas, que estao vindo do "main" global
    ContaCorrente contaCorrente = new ContaCorrente(GerenciamentoContaBancaria.contaCorrenteUsuario, taxaManutencao);
    ContaPoupanca contaPoupanca = new ContaPoupanca(GerenciamentoContaBancaria.contaPoupancaUsuario, taxaJuros);
    
    /**
     * Creates new form FormMain
     */
    public FormMain() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu = new javax.swing.JPopupMenu();
        jMenuItemCC = new javax.swing.JMenuItem();
        jSeparator = new javax.swing.JPopupMenu.Separator();
        jMenuItemCP = new javax.swing.JMenuItem();
        jPanelBankTitle = new javax.swing.JPanel();
        jLabelBankName = new javax.swing.JLabel();
        jPanelDiaNoite = new javax.swing.JPanel();
        jLabelBankName1 = new javax.swing.JLabel();
        jLabelBankName2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanelMain = new javax.swing.JPanel();
        btnDepositar = new javax.swing.JButton();
        btnExtrato = new javax.swing.JButton();
        btnTransferencia = new javax.swing.JButton();
        btnPagamentos = new javax.swing.JButton();
        btnSaqueCC = new javax.swing.JButton();
        btnSaqueCP = new javax.swing.JButton();
        btnSaldo = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        jPanelTitle = new javax.swing.JPanel();
        jLabelTitle = new javax.swing.JLabel();
        jPanelSeparator = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();
        LabelAutor = new javax.swing.JLabel();

        jMenuItemCC.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        jMenuItemCC.setText("Conta Corrente");
        jMenuItemCC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCCActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuItemCC);
        jPopupMenu.add(jSeparator);

        jMenuItemCP.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        jMenuItemCP.setText("Conta poupança");
        jMenuItemCP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jMenuItemCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCPActionPerformed(evt);
            }
        });
        jPopupMenu.add(jMenuItemCP);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciamento Conta Bancaria");
        setBackground(new java.awt.Color(28, 23, 20));
        setResizable(false);

        jPanelBankTitle.setBackground(new java.awt.Color(0, 204, 153));
        jPanelBankTitle.setMaximumSize(new java.awt.Dimension(32767, 67));

        jLabelBankName.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabelBankName.setText("Bradesco");

        jPanelDiaNoite.setBackground(new java.awt.Color(0, 204, 153));
        jPanelDiaNoite.setPreferredSize(new java.awt.Dimension(100, 67));

        jLabelBankName1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabelBankName1.setText("Dia");

        jLabelBankName2.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabelBankName2.setText("Noite");

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("&");

        javax.swing.GroupLayout jPanelDiaNoiteLayout = new javax.swing.GroupLayout(jPanelDiaNoite);
        jPanelDiaNoite.setLayout(jPanelDiaNoiteLayout);
        jPanelDiaNoiteLayout.setHorizontalGroup(
            jPanelDiaNoiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiaNoiteLayout.createSequentialGroup()
                .addGap(3, 3, 3)
                .addComponent(jLabelBankName1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelBankName2)
                .addGap(26, 26, 26))
        );
        jPanelDiaNoiteLayout.setVerticalGroup(
            jPanelDiaNoiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelDiaNoiteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabelBankName1, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
                .addComponent(jLabelBankName2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        javax.swing.GroupLayout jPanelBankTitleLayout = new javax.swing.GroupLayout(jPanelBankTitle);
        jPanelBankTitle.setLayout(jPanelBankTitleLayout);
        jPanelBankTitleLayout.setHorizontalGroup(
            jPanelBankTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelBankTitleLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabelBankName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanelDiaNoite, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanelBankTitleLayout.setVerticalGroup(
            jPanelBankTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabelBankName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelDiaNoite, javax.swing.GroupLayout.DEFAULT_SIZE, 47, Short.MAX_VALUE)
        );

        btnDepositar.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        btnDepositar.setText("Depositar");
        btnDepositar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDepositar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDepositarActionPerformed(evt);
            }
        });

        btnExtrato.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        btnExtrato.setText("Extratos");
        btnExtrato.setEnabled(false);

        btnTransferencia.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        btnTransferencia.setText("Transferências");
        btnTransferencia.setEnabled(false);

        btnPagamentos.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        btnPagamentos.setText("Pagamentos");
        btnPagamentos.setEnabled(false);

        btnSaqueCC.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        btnSaqueCC.setText("Saque da Conta-Corrente");
        btnSaqueCC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaqueCC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaqueCCActionPerformed(evt);
            }
        });

        btnSaqueCP.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        btnSaqueCP.setText("Saque da Conta-Poupança");
        btnSaqueCP.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaqueCP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaqueCPActionPerformed(evt);
            }
        });

        btnSaldo.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        btnSaldo.setText("Saldo");
        btnSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaldoActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("SF Pro Display", 1, 14)); // NOI18N
        btnSair.setText("Sair");
        btnSair.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        jPanelTitle.setBackground(new java.awt.Color(204, 204, 204));

        jLabelTitle.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabelTitle.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTitle.setText("Selecione a opção desejada:");

        javax.swing.GroupLayout jPanelTitleLayout = new javax.swing.GroupLayout(jPanelTitle);
        jPanelTitle.setLayout(jPanelTitleLayout);
        jPanelTitleLayout.setHorizontalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelTitleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanelTitleLayout.setVerticalGroup(
            jPanelTitleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelTitleLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabelTitle)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSaqueCP, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSaqueCC, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
            .addComponent(jPanelTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanelMainLayout.setVerticalGroup(
            jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(btnSaqueCC, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaqueCP, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelMainLayout.createSequentialGroup()
                        .addComponent(btnDepositar, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnExtrato, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTransferencia, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPagamentos, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanelSeparator.setBackground(new java.awt.Color(255, 0, 0));
        jPanelSeparator.setAlignmentX(0.0F);
        jPanelSeparator.setAlignmentY(0.0F);
        jPanelSeparator.setFocusable(false);
        jPanelSeparator.setPreferredSize(new java.awt.Dimension(0, 4));

        javax.swing.GroupLayout jPanelSeparatorLayout = new javax.swing.GroupLayout(jPanelSeparator);
        jPanelSeparator.setLayout(jPanelSeparatorLayout);
        jPanelSeparatorLayout.setHorizontalGroup(
            jPanelSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanelSeparatorLayout.setVerticalGroup(
            jPanelSeparatorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 4, Short.MAX_VALUE)
        );

        LabelAutor.setFont(new java.awt.Font("SF Pro Display", 1, 12)); // NOI18N
        LabelAutor.setForeground(new java.awt.Color(153, 153, 153));
        LabelAutor.setText("Manoel Pereira dos Santos");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanelBankTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanelSeparator, javax.swing.GroupLayout.DEFAULT_SIZE, 666, Short.MAX_VALUE)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LabelAutor, javax.swing.GroupLayout.PREFERRED_SIZE, 654, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelBankTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanelSeparator, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanelMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabelAutor)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDepositarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDepositarActionPerformed
        
        //Exibo o menu com as opções de depositar na conta corrente e conta poupança
        jPopupMenu.show(btnDepositar, 0, btnDepositar.getHeight());
    }//GEN-LAST:event_btnDepositarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        // Chamando System.exit(0) para encerrar todo o sistema
        System.exit(0);
    }//GEN-LAST:event_btnSairActionPerformed

    private void jMenuItemCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCCActionPerformed
        
        tituloJanela = "CONTA CORRENTE";
        
        //Realizo a obtenção do valor a ser depositado da conta (convertendo o valor digitado para double)
        deposito = Double.parseDouble(JOptionPane.showInputDialog(null, "DEPÓSITO\n\nDigite o valor R$:", tituloJanela, JOptionPane.PLAIN_MESSAGE));
        
        // Realização de depósitos na conta
        contaCorrente.depositar(deposito);
        
    }//GEN-LAST:event_jMenuItemCCActionPerformed

    private void jMenuItemCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCPActionPerformed
        
        tituloJanela = "CONTA POUPANÇA";
        
        //Realizo a obtenção do valor a ser depositado da conta (convertendo o valor digitado para double)
        deposito = Double.parseDouble(JOptionPane.showInputDialog(null, "DEPÓSITO\n\nDigite o valor R$:", tituloJanela, JOptionPane.PLAIN_MESSAGE));
        
        // Realização de depósitos na conta
        contaPoupanca.depositar(deposito);
        
        // Aplica os juros no valor da conta poupança
        contaPoupanca.calcularJuros();
        
        //Infomo uma mensagem na tela informando que a conta do usuario já está rendendo
        JOptionPane.showMessageDialog(this, "Parabens!!! \n\n "
                + "Seu saldo já está rendendo incríveis 5%\n\n\n Consulte seu saldo para mais informações.", 
                tituloJanela, JOptionPane.INFORMATION_MESSAGE);
                  
    }//GEN-LAST:event_jMenuItemCPActionPerformed

    private void btnSaqueCCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaqueCCActionPerformed
        
        tituloJanela = "CONTA CORRENTE";
        
        //Realizo a obtenção do valor a ser sacado da conta (convertendo o valor digitado para double)
        saque = Double.parseDouble(JOptionPane.showInputDialog(null, "SAQUE\n\nDigite o valor R$:", tituloJanela, JOptionPane.PLAIN_MESSAGE));
        saldo = contaCorrente.obterSaldo();
                
        if(saque + taxaManutencao > saldo) {
            JOptionPane.showMessageDialog(this, "Saldo insuficiente. Saque não realizado.\n" +"Seu saldo é de R$ " + 
                    saldo +"\n\nTaxa de manutenção da conta R$ " + taxaManutencao , tituloJanela, JOptionPane.ERROR_MESSAGE);
        }else if(contaCorrente.sacar(saque)){
            
            // Aplica a taxa de manutenção na conta corrente ao sacar
            contaCorrente.aplicarTaxaManutencao();
            
            JOptionPane.showMessageDialog(this, "Saque de R$ " + saque +" efetuado com sucesso!\n\n Foi cobrado R$ " + 
                    taxaManutencao + " de taxa de manutenção da conta\n\n\nConsulte seu saldo para mais informações.", 
                    tituloJanela, JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, "Saldo insuficiente. Saque não realizado.", tituloJanela, JOptionPane.ERROR_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSaqueCCActionPerformed

    private void btnSaqueCPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaqueCPActionPerformed
    
        tituloJanela = "CONTA POUPANÇA";

        //Realizo a obtenção do valor a ser sacado da conta (convertendo o valor digitado para double)
        saque = Double.parseDouble(JOptionPane.showInputDialog(null, "SAQUE\n\nDigite o valor R$:", tituloJanela, JOptionPane.PLAIN_MESSAGE));
        saldo = contaPoupanca.obterSaldo();
        
        if(saque > saldo) {
            JOptionPane.showMessageDialog(this, "Saldo insuficiente. Saque não realizado.\n" +"Seu saldo é de R$ " + 
                    saldo +"\n\nSaque isento de Taxa de manutenção de conta",tituloJanela, JOptionPane.ERROR_MESSAGE);
        }else if(contaPoupanca.sacar(saque)){
            JOptionPane.showMessageDialog(this, "Saque de R$ " + saque +" efetuado com sucesso!\n\nSaque isento de Taxa de manutenção", tituloJanela, JOptionPane.INFORMATION_MESSAGE);
        }
        
    }//GEN-LAST:event_btnSaqueCPActionPerformed

    private void btnSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaldoActionPerformed
        
        tituloJanela = "SALDO";
        
        System.out.print(contaPoupanca.obterSaldo());
        
        JOptionPane.showMessageDialog(this, "\n SALDO CONTA CORRENTE("+ contaCorrente.obterConta()+") : R$ " + 
                contaCorrente.obterSaldo() +"\n\n SALDO CONTA POUPANÇA("+ contaPoupanca.obterConta()+") : R$ " + 
                contaPoupanca.obterSaldo() ,tituloJanela, JOptionPane.PLAIN_MESSAGE);
        
    }//GEN-LAST:event_btnSaldoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LabelAutor;
    private javax.swing.JButton btnDepositar;
    private javax.swing.JButton btnExtrato;
    private javax.swing.JButton btnPagamentos;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSaldo;
    private javax.swing.JButton btnSaqueCC;
    private javax.swing.JButton btnSaqueCP;
    private javax.swing.JButton btnTransferencia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelBankName;
    private javax.swing.JLabel jLabelBankName1;
    private javax.swing.JLabel jLabelBankName2;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JMenuItem jMenuItemCC;
    private javax.swing.JMenuItem jMenuItemCP;
    private javax.swing.JPanel jPanelBankTitle;
    private javax.swing.JPanel jPanelDiaNoite;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelSeparator;
    private javax.swing.JPanel jPanelTitle;
    private javax.swing.JPopupMenu jPopupMenu;
    private javax.swing.JPopupMenu.Separator jSeparator;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
